version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  terraform: ovotech/terraform@1.5

workflows:
  build:
    jobs:
      - gcp-gcr/build-and-push-image:
          name: app_build
          context: staging
          image: berlioz-app
          dockerfile: ./app/Dockerfile
          tag: ${CIRCLE_SHA1}
          path: app
          registry-url: us.gcr.io
      - gcp-gcr/build-and-push-image:
          name: web_build
          context: staging
          image: berlioz-web
          dockerfile: web/Dockerfile
          tag: ${CIRCLE_SHA1}
          path: web
          registry-url: us.gcr.io
      - terraform/apply:
          context: staging
          path: terraform
          var: app_image=us.gcr.io/berlioz-app:${CIRCLE_SHA1},web_image=us.gcr.io/berlioz-web:${CIRCLE_SHA1}
          filters:
            branches:
              only: master
          requires:
            - app_build
            - web_build

