version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  terraform: ovotech/terraform@1.5

jobs:
  terraform_apply:
    executor: terraform/terraform-0_12
    environment:
      TF_VAR_gcp_project_id: ${GOOGLE_PROJECT_ID}
      TF_VAR_gcp_region: ${GOOGLE_COMPUTE_REGION}
    steps:
      - checkout
      - run:
          name: Select terraform version
          command: tfswitch 0.12.10
      - terraform/apply:
          path: terraform
          auto_approve: true
          backend_config: bucket="${TF_STATE_GCS_BUCKET}",prefix="terraform/state"
          var_file: terraform/terraform.tfvars
          var: app_image=us.gcr.io/${GOOGLE_PROJECT_ID}/berlioz-app:${CIRCLE_SHA1},web_image=us.gcr.io/${GOOGLE_PROJECT_ID}/berlioz-web:${CIRCLE_SHA1}

workflows:
  build:
    jobs:
      - gcp-gcr/build-and-push-image:
          name: app_build
          context: staging
          image: berlioz-app
          dockerfile: ./app/Dockerfile
          tag: ${CIRCLE_SHA1}
          path: app
          registry-url: us.gcr.io
      - gcp-gcr/build-and-push-image:
          name: web_build
          context: staging
          image: berlioz-web
          dockerfile: web/Dockerfile
          tag: ${CIRCLE_SHA1}
          path: web
          registry-url: us.gcr.io
      - terraform_apply:
          context: staging
          filters:
            branches:
              only: master
          requires:
            - app_build
            - web_build

