apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-schema
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.backend.name }}
data:
  dump: |-
    CREATE DATABASE IF NOT EXISTS demo;

    USE demo;

    CREATE TABLE IF NOT EXISTS contacts (
        id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name varchar(100),
        phone varchar(100)
        );
