{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: database*/}}
{{/*  namespace: {{ .Release.namespace }}*/}}
{{/*data:*/}}
{{/*  MYSQL_HOST: {{ .Values.database.address | b64enc }}*/}}
{{/*  MYSQL_DB: {{ .Values.database.name | b64enc }}*/}}
{{/*  MYSQL_USER: {{ .Values.database.user | b64enc }}*/}}
{{/*  MYSQL_PASSWORD: {{ .Values.database.password | b64enc }}*/}}
{{/*  MYSQL_PORT: {{ .Values.database.port | quote | b64enc }}*/}}
